### index method
GET http://localhost:3000/anime

### create method
POST http://localhost:3000/anime
Content-Type: application/json

{
  "title": "Naruto Shippuden"
}

### show method
GET http://localhost:3000/anime/2