### index method
GET http://localhost:3000/anime

### create method
POST http://localhost:3000/anime
Content-Type: application/json

{
  "title": "That Time I Got Reincarnated as a Slime",
  "creator": "Fuse and Mitz Vah",
  "genre": "action, adventure, comedy, fantasy",
  "demographic": "shounen",
  "original": false
}