### index method
GET http://localhost:3000/anime

### create method
POST http://localhost:3000/anime
Content-Type: application/json

{
  "title": "Demon Slayer",
  "creator": "Koyoharu Gotouge",
  "genre": "action, supernatural",
  "demographic": "shounen",
  "original": "false",
  "japanese_title": "鬼滅の刃",
  "premiered": "2019-4-6"
}

### show method
GET http://localhost:3000/anime/2

### update method
PATCH http://localhost:3000/anime/1
Content-Type: application/json

{
  "genre": "action, adventure, comedy, ninja"
}

### destroy method
DELETE http://localhost:3000/anime
